### ISSUE TITLE
Desk Class

### ISSUE THREAD

**Issue by jbkoh** [BuildSysUniformMetadata/Brick#15]
Suggested by @blip2 
Previous thread: #https://github.com/BuildSysUniformMetadata/GroundTruth/issues/5
tl;dr: Adding Desk as a class under Equipment. There are sensor-enabled furniture these days. Such furniture would be useful to provide better occupancy estimation and temperature controls. Thoughts?

**Comment by gtfierro** [comment]
I think its a pretty straightforward evolution of the schema. I like the idea of a "Furniture" class:

```
Equipment
     |
     +---> Furniture
           |       |
           v       v
           Chair  Desk
```

and then we can have `hasPoint` relationships coming off of instances of those classes in order to associate sensors with them. The furniture can also have `isLocatedIn` relationships with instances from the spatial hierarchy.

There's probably no need for intermediary classes between Equipment/Furniture/{Chair, Desk}, but we could expand subclasses of Furniture to include others, and we can further subclass Chair or Desk as necessary.
