### ISSUE TITLE
Change isLocatedIn to hasLocation

### ISSUE THREAD

**Issue by bbalaji-ucsd** [BuildSysUniformMetadata/Brick#24]
hasLocation has a nice inverse "isLocationOf"

It's also part of W3C DUL standard: https://www.w3.org/2005/Incubator/ssn/ssnx/ssn#hasLocation

**Comment by gtfierro** [comment]
Fixing this issue will require changing all existing example Brick files and buildings.

**Comment by bbalaji-ucsd** [comment]
Yes, agreed. Should be a simple substitution though. Doesn’t touch any
logic.

- Bharath

**Comment by jbkoh** [comment]
At this moment, I'd like to replace ``isLocatedIn`` with ``hasLocation``, and ``contains`` with ``isLocationOf`` because

- ``contains`` is confused with ``isPartOf``
- Having equivalent properties would be computationally wasteful with more latencies.
- We have specified the versions. One can relate the previous version's ``isLocatedIn`` with the current version of ``hasLocation``.
    - Even more concretely, we can provide a version graph of TagSets/Properties though it would take time to develop.

**Comment by gtfierro** [comment]
I like this change. Shall we shoot for this landing in 1.0.3? I'd like to bundle a bunch of these changes together

**Comment by jbkoh** [comment]
Yes. I am compiling those updates here:
https://github.com/jbkoh/Brick/tree/1.0.3



With regards,
Jason Koh

**Comment by jbkoh** [comment]
Closing by https://github.com/BuildSysUniformMetadata/Brick/pull/42
