### ISSUE TITLE
RFC: Add shading devices

### ISSUE THREAD

**Issue by blip2** [BuildSysUniformMetadata/Brick#30]
There doesn't seem to be a class to define shading devices e.g. automated blinds or adjustable brise soleil - should be a fairly straightforward definition for the equipment:

Equipment>Adjustable Shading
Equipment>Adjustable Shading>Blind
Equipment>Adjustable Shading>Louver

The control and measurement definitions would be very similar to a Damper (position, limit sensor/setpoints, command)

**Comment by jbkoh** [comment]
This looks straight-forward and necessary. 
- What about "Shading System" with 
removing Adjustable as it is obvious (or not meaningful)
and adding System to clarify this is a system (or device)?

- I made this as an RFC as I think it is self-contained.

**Comment by jbkoh** [comment]
Hi, @blip2 

I am sorry that it's been a while (maybe too much) since you issued this. Are the above TagSets sufficient enough for the relavant systems? They look reasonable and useful. I also saw three Points from your commit at your fork, Shading_System_Command, Shading_System_Position_Sensor, and Shading_System_Position_Setpoint. Are they sufficient enough for your system? 

If there is no further comments, I will assume the TagSets suggested so far are enough and soon add this RFC to a milestone.

Thanks!

**Comment by blip2** [comment]
Hi, @jbkoh - Yes I think those listed are sufficient, the only other thing might be for a general fault/alarm from the controller but I think something like Fault_Indicator_Status would suffice.

**Comment by jbkoh** [comment]
@blip2 I apologize that I've been ignorant of this issue. I am resolving the remaining issues for a minor version update. I found that Louver is often regarded as a type of Blind. https://en.wikipedia.org/wiki/Louver

Do you think placing Louver as a subclass of Blind is reasonable?
Shading System>Blind>Louver

I will add those very soon. (It should haven't taken this long...)

**Comment by jbkoh** [comment]
I made the hierarchy as Shading System>Blind>Louver. If there are any other opinions, please create a new issue. It's included in https://github.com/BuildSysUniformMetadata/Brick/pull/42

Thank you!
